[build]
  base = "frontend"
  command = "npm run build" 
  publish = "build"

[context.production]
  publish = "output/"
  command = "make publish"
  environment = { NODE_VERSION = "14.15.3", REACT_APP_RECAPTCHA_SITEKEY = "$RECAPTCHA_SITEKEY" }  # Add the environment variable here
