[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[context.production]
  publish = "output/"
  command = "make publish"
  environment = { NODE_VERSION = "14.15.3", RECAPTCHA_SITEKEY = "6LdOyW8nAAAAANOttt8BDu--N5t_egosjAoanPe0" }
